[build]
  command = "npm install"
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."generate-preview"]
  external_node_modules = []

[functions."story-worker-background"]
  external_node_modules = []

[functions."generate-full"]
  external_node_modules = ["stripe"]

[functions."full-worker-background"]
  external_node_modules = []

[functions."preview-worker-background"]
  external_node_modules = []

[functions."create-discount"]
  external_node_modules = ["stripe"]

[functions."stripe-webhook"]
  external_node_modules = ["stripe"]


[[edge_functions]]
  path = "/"
  function = "og-shared"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
